### ISSUE TITLE
Calculate bottom up

### ISSUE THREAD

**Issue by ajreading** [castlegateit/jquery-uniformify#1]
Currently, only elements with the same top offset can be made to be uniform height. It would be extremely useful in situations where elements are positioned absolutely to the bottom of an element if the calculations could be reversed to work bottom up instead of top down.

![image](https://cloud.githubusercontent.com/assets/363404/23296338/6941e480-fa6c-11e6-8f9d-6a96a5da0bb5.png)

**Comment by johnkhughes** [comment]
The problem with this feature is that the height of the box would affect its bottom offset, which would normally be a problem. And now that we can use flexbox, this plugin is actually becoming redundant. So I'm going to close this one.
